<?php

namespace App\Console\Commands;

use App\Models\Category;
use App\Models\Product;
use App\Support\WiboostCatalog;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class SetupWiboostCatalog extends Command
{
    protected $signature = 'wiboost:setup-catalog {--refresh-logos : Replace autogenerated subcategory logos}';

    protected $description = 'Siapkan struktur kategori, sub-kategori berlogo, dan template produk manual untuk katalog Wiboost';

    public function handle(): int
    {
        $this->info('Menyiapkan struktur katalog Wiboost...');

        DB::transaction(function () {
            $this->ensureTopCategories();
            $this->ensureSubcategories();
            $this->assignExistingProductsToSubcategories();
            $this->ensureManualTemplates();
            $this->cleanupDeprecatedCategories();
        });

        $this->info('Struktur katalog selesai disiapkan.');

        return self::SUCCESS;
    }

    protected function ensureTopCategories(): void
    {
        foreach (WiboostCatalog::coreCategories() as $definition) {
            $category = Category::query()->firstOrNew([
                'slug' => $definition['slug'],
            ]);

            $category->fill([
                'parent_id' => null,
                'name' => $definition['name'],
                'description' => $category->description ?: $definition['description'],
                'emote' => $definition['emote'],
                'fulfillment_type' => $definition['fulfillment_type'],
            ]);

            $category->save();
        }
    }

    protected function ensureSubcategories(): void
    {
        foreach (WiboostCatalog::subcategories() as $parentSlug => $subcategories) {
            $parent = Category::query()->where('slug', $parentSlug)->first();

            if (! $parent) {
                continue;
            }

            foreach ($subcategories as $definition) {
                $category = Category::query()->firstOrNew([
                    'slug' => $definition['slug'],
                ]);

                $generatedLogoPath = 'categories/generated/' . $definition['slug'] . '.svg';
                $shouldRefreshLogo = $this->option('refresh-logos')
                    || blank($category->image)
                    || str_starts_with((string) $category->image, 'categories/generated/');

                if ($shouldRefreshLogo) {
                    Storage::disk('public')->put(
                        $generatedLogoPath,
                        $this->buildLogoSvg(
                            $definition['name'],
                            $definition['logo_text'],
                            $definition['logo_background'],
                            $definition['logo_foreground'],
                        )
                    );
                }

                $category->fill([
                    'parent_id' => $parent->id,
                    'name' => $definition['name'],
                    'description' => $definition['description'],
                    'emote' => null,
                    'image' => $shouldRefreshLogo ? $generatedLogoPath : $category->image,
                    'fulfillment_type' => $parent->fulfillment_type,
                ]);

                $category->save();
            }
        }
    }

    protected function assignExistingProductsToSubcategories(): void
    {
        Product::query()
            ->with('category.parent')
            ->where('provider_source', 'ordersosmed')
            ->where('process_type', 'api')
            ->chunkById(200, function ($products) {
                foreach ($products as $product) {
                    $subcategorySlug = WiboostCatalog::resolveOrdersosmedSubcategorySlug(
                        $product->name,
                        $this->extractProviderCategory($product->description),
                        (string) $product->description,
                    );

                    $categoryId = Category::query()->where('slug', $subcategorySlug)->value('id');

                    if ($categoryId && (int) $product->category_id !== (int) $categoryId) {
                        $product->update([
                            'category_id' => $categoryId,
                        ]);
                    }
                }
            });

        Product::query()
            ->with('category.parent')
            ->where('provider_source', 'digiflazz')
            ->chunkById(200, function ($products) {
                foreach ($products as $product) {
                    $topCategorySlug = $this->resolveProductTopCategorySlug($product);

                    if (! $topCategorySlug) {
                        continue;
                    }

                    $subcategorySlug = WiboostCatalog::resolveDigiflazzSubcategorySlug(
                        $topCategorySlug,
                        $product->name,
                        $product->provider_product_id ?? '',
                        (string) $product->description,
                    );

                    $categoryId = $subcategorySlug
                        ? Category::query()->where('slug', $subcategorySlug)->value('id')
                        : null;

                    if ($categoryId && (int) $product->category_id !== (int) $categoryId) {
                        $product->update([
                            'category_id' => $categoryId,
                        ]);
                    }
                }
            });
    }

    protected function ensureManualTemplates(): void
    {
        foreach (WiboostCatalog::manualProductTemplates() as $template) {
            $category = Category::query()->where('slug', $template['subcategory_slug'])->first();

            if (! $category) {
                continue;
            }

            $attributes = [
                'category_id' => $category->id,
                'name' => $template['name'],
                'provider_source' => null,
                'provider_product_id' => null,
            ];

            $product = Product::query()->firstOrNew($attributes);
            $targetMeta = WiboostCatalog::targetMetaForTopCategory($template['top_category_slug']);

            if (! $product->exists) {
                $product->slug = Str::slug($template['name']) . '-' . Str::lower(Str::random(5));
            }

            $product->fill([
                'provider_id' => null,
                'process_type' => $template['process_type'],
                'description' => $template['description'] . "\n\nTemplate ini dibuat otomatis. Atur harga, aktivasi produk, dan isi stok / brief sesuai kebutuhan dari panel admin.",
                'price' => 0,
                'is_active' => false,
                'status' => 'inactive',
                'stock_reminder' => in_array($template['process_type'], ['account', 'number'], true) ? 1 : 0,
                'target_label' => $template['process_type'] === 'manual' ? ($targetMeta['label'] ?? null) : null,
                'target_placeholder' => $template['process_type'] === 'manual' ? ($targetMeta['placeholder'] ?? null) : null,
                'target_hint' => $template['process_type'] === 'manual' ? ($targetMeta['hint'] ?? null) : null,
            ]);

            $product->save();
        }
    }

    protected function cleanupDeprecatedCategories(): void
    {
        Category::query()
            ->whereIn('slug', WiboostCatalog::deprecatedCategorySlugs())
            ->orderByDesc('parent_id')
            ->get()
            ->each(function (Category $category) {
                if ($category->products()->exists() || $category->children()->exists()) {
                    return;
                }

                if ($category->image && str_starts_with((string) $category->image, 'categories/generated/')) {
                    Storage::disk('public')->delete($category->image);
                }

                $category->delete();
            });
    }

    protected function resolveProductTopCategorySlug(Product $product): ?string
    {
        $category = $product->category;

        if (! $category) {
            return null;
        }

        while ($category->parent) {
            $category = $category->parent;
        }

        return $category->slug;
    }

    protected function extractProviderCategory(?string $description): string
    {
        if (! $description) {
            return '';
        }

        if (preg_match('/Kategori provider:\s*(.+)$/mi', $description, $matches) === 1) {
            return trim($matches[1]);
        }

        return '';
    }

    protected function buildLogoSvg(string $name, string $logoText, string $background, string $foreground): string
    {
        $safeName = e($name);
        $safeText = e($logoText);

        return <<<SVG
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" role="img" aria-label="{$safeName}">
  <rect width="256" height="256" rx="56" fill="{$background}" />
  <circle cx="128" cy="128" r="94" fill="rgba(255,255,255,0.14)" />
  <text x="128" y="138" text-anchor="middle" fill="{$foreground}" font-family="Arial, sans-serif" font-size="74" font-weight="700" letter-spacing="2">{$safeText}</text>
</svg>
SVG;
    }
}
